server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hou2021
  jpa:
    show-sql: true
    properties:
      hibernate:
        #hibernate方言
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: basics-tool
logging:
  level:
    #解决swagger报错问题
    io.swagger.models.parameters.AbstractSerializableParameter: error
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000