
spring:
  application:
    name: optim-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #将路径为Path=/api/basics-web转发basics-web微服务
        - id: basics-web
          uri: lb://basics-web
          predicates:
            - Path=/basics-web/api/v1/**
          filters:
            - RewritePath=/basics-web/(?<segment>/?.*),/$\{segment}
        - id: basics-sms
          uri: lb://basics-sms
          predicates:
            - Path=/basics-sms/api/v1/**
          filters:
            - RewritePath=/basics-sms/(?<segment>/?.*),/$\{segment}
        - id: basics-token
          uri: lb://basics-token
          predicates:
            - Path=/basics-token/**
          filters:
            - RewritePath=/basics-token/(?<segment>/?.*),/$\{segment}
server:
  port: 88
