server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hou2021
  jpa:
    show-sql: true
    properties:
      hibernate:
        #hibernate方言
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect