server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hou2021
  jpa:
    show-sql: true
    properties:
      hibernate:
        #hibernate方言
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
  application:
    name: basics-token
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    #解决swagger报错问题
    io.swagger.models.parameters.AbstractSerializableParameter: error
